# Build all Prim targets.
# 
# Author: H Paterson.
# Copyright: Boost Software License 1.0.
# Date: 19/10/19.

trigger:
- master

jobs:

- job: windows_vs_build
  displayName: Build Prim on Windows with Visual Studio.
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CMake@1
    displayName: 'Generate project files with CMake'
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '..'
  - task: VSBuild@1
    displayName: 'Build project with VSBuild'
    inputs:
      solution: '**\*.sln'
      maximumCpuCount: true
      configuration: 'debug'
      msbuildArgs: '-property:WarningLevel=4'

- job: linux_make_build
  displayName: Build Prim on Linux with make.
  pool:
    vmImage: 'ubuntu-latest'
    steps:
    - task: CMake@1
      displayName: Generate make files with CMake'
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '..'
