# Build all Prim targets.
# 
# Author: H Paterson.
# Copyright: Boost Software License 1.0.
# Date: 19/10/19.

trigger:
- master

pool:
  vmImage: 'windows-latest'
  
steps:
- task: CMake@1
  displayName: 'Generate project files with CMake'
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'

- task: VSBuild@1
  displayName: 'Build project with VSBuild'
  inputs:
    solution: '**\*.sln'
    maximumCpuCount: true
    configuration: 'debug'
    msbuildArgs: '/p:WarningLevel=4;warningsAsErrors=true'
