# Build all Prim targets.
# 
# Author: H Paterson.
# Copyright: Boost Software License 1.0.
# Date: 19/10/19.

trigger:
- master

jobs:

- job: windows_vs_build
  displayName: Windows-VS build
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CMake@1
    displayName: 'Generate project files with CMake'
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '..'
  - task: VSBuild@1
    displayName: 'Build Prim with VSBuild'
    inputs:
      solution: '**\*.sln'
      maximumCpuCount: true
      configuration: 'debug'
      msbuildArgs: '-property:WarningLevel=4'

- job: linux_make_build
  displayName: Linix-make build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CMake@1
    displayName: Generate make files with CMake
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '..''
   - task: CmdLine@2
     displayName: Build Prim with make
     inputs:
       script: make
       workingDirectory: build
